"""
Topic model for storing BERTopic-generated topics.
"""
from sqlalchemy import Column, String, DateTime, Integer, Text
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from database import Base


class Topic(Base):
    """
    Represents a topic generated by BERTopic.

    Attributes:
        id: Primary key
        name: Human-readable topic name (from OpenAI)
        description: Detailed topic description
        wish_count: Number of wishes in this topic
        embedding_model: Name of embedding model used
        topic_model_id: BERTopic model ID
        created_at: Timestamp when topic was created
        updated_at: Timestamp when topic was last updated
    """

    __tablename__ = "topics"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    wish_count = Column(Integer, default=0)
    embedding_model = Column(String(100), nullable=True)
    topic_model_id = Column(String(100), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Relationships
    wishes = relationship("Wish", back_populates="topic")
    topic_associations = relationship(
        "TopicWish",
        back_populates="topic",
        cascade="all, delete-orphan"
    )

    def __repr__(self):
        return f"<Topic(id={self.id}, name={self.name})>"
